### ISSUE TITLE
Not able to run on ARM M1 Mac

### ISSUE THREAD

**Issue by quankhuc** [OysterHQ/FastAPI-Production-Boilerplate#4]
Hi,

Thank you for making a production grade boilerplate available. I ran into troubles when I tried to start this project on my Mac M1 computer. It seems to me that there is a configuration that you have on the project is for machine of type x86-64, when the `poetry enviroment` is set up. How can I change the configuration to install packages for M1 machine?

Steps to reproduce:

Follow the jump start instruction at README. When running `make migrate`, this error happened:

```Traceback (most recent call last):
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/quankhuc/FastAPI-Production-Boilerplate/migrations/env.py", line 29, in <module>
    from app.models import Base
  File "/Users/quankhuc/FastAPI-Production-Boilerplate/app/models/__init__.py", line 1, in <module>
    from core.database import Base
  File "/Users/quankhuc/FastAPI-Production-Boilerplate/core/database/__init__.py", line 1, in <module>
    from .session import (
  File "/Users/quankhuc/FastAPI-Production-Boilerplate/core/database/session.py", line 30, in <module>
    "writer": create_async_engine(config.POSTGRES_URL, pool_recycle=3600),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 85, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 720, in create_engine
    event.listen(pool, "connect", on_connect)
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/event/api.py", line 124, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/event/registry.py", line 310, in listen
    self.dispatch_target.dispatch._listen(self, *args, **kw)
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/event/base.py", line 177, in _listen
    return self._events._listen(event_key, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/events.py", line 94, in _listen
    event_key.base_listen(**kw)
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/event/registry.py", line 348, in base_listen
    for_modify._set_asyncio()
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/event/attr.py", line 416, in _set_asyncio
    self._exec_once_mutex = AsyncAdaptedLock()
                            ^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/util/concurrency.py", line 63, in AsyncAdaptedLock
    _not_implemented()
  File "/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/sqlalchemy/util/concurrency.py", line 43, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function. dlopen(/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/greenlet/_greenlet.cpython-311-darwin.so, 0x0002): tried: '/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/greenlet/_greenlet.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/greenlet/_greenlet.cpython-311-darwin.so' (no such file), '/Users/quankhuc/Library/Caches/pypoetry/virtualenvs/fastapi-boilerplate-ncg74GX8-py3.11/lib/python3.11/site-packages/greenlet/_greenlet.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
make: *** [migrate] Error 1```

**Comment by iam-abbas** [comment]
It is asking you to install `greenlet` can you try
```
pip install greenlet
```

**Comment by quankhuc** [comment]
I got it working with using conda enviroment instead of poetry enviroment. I don't know why it seems to me poetry might not be able to install compatible packages with M1 chip laptops?

**Comment by quankhuc** [comment]
I want to run this server without using docker but in multiple shells. I have run the server by running `python main.py` and try to run migration by running `make migrate`. However, it give me this error:
```
poetry run alembic upgrade head
Traceback (most recent call last):
  File "/Users/quankhuc/anaconda3/envs/TradingBot/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/quankhuc/FastAPI-Production-Boilerplate/migrations/env.py", line 86, in <module>
    asyncio.run(run_migrations_online())
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/quankhuc/FastAPI-Production-Boilerplate/migrations/env.py", line 77, in run_migrations_online
    async with connectable.connect() as connection:
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py", line 127, in __aenter__
    return await self.start(is_ctxmanager=True)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 268, in start
    await greenlet_spawn(self.sync_engine.connect)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 893, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 5432)
make: *** [migrate] Error 1
```

Do I miss a step that I need to run the database? Because the port and host seems to me are the port and host of a postgres server.
